language: ruby
rvm:
  - 2.6.3
cache:
  bundler: true
  yarn: true
addons:
  postgresql: 11.5
before_script:
  - psql -c 'create database PoubellesBattle_test;' -U postgres
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
