language: ruby
rvm:
  - 2.6.3
cache:
  bundler: true
  yarn: true
services:
  - postgresql
addons:
  postgresql: '11.5'
env:
    global:
      - PGPORT=5433
before_script:
  - cp config/database.yml.travis config/database.yml
script:
  - bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
  - bundle exec rspec
